"""Reusable helpers for the Portuguese simile candidate MVP."""

from tal_qual.bronze import (
    BRONZE_OUTPUT_PATH,
    RAW_CORPUS_GLOB,
    RAW_CORPUS_INPUT,
    prepare_bronze_dataframe,
    write_bronze_parquet,
)
from tal_qual.refinement import (
    ONE_SHARD_REFINED_TIER,
    REFINED_CANDIDATES_NLP_OUTPUT_PATH,
    SAMPLE_DEBUG_TIER,
    build_nlp_parse_text,
    nlp_refinement_scope,
    prepare_refined_dataframe,
    prepare_refined_dataframe_for_tier,
    prepare_sample_debug_dataframe,
    refine_candidate_row,
    refine_candidate_rows,
    sample_debug_rows,
    write_refined_parquet,
)
from tal_qual.silver import (
    SILVER_OUTPUT_PATH,
    connector_family_counts_dataframe,
    extract_candidate_rows,
    normalize_vehicle,
    pattern_type_counts_dataframe,
    prepare_silver_dataframe,
    sample_examples_dataframe,
    top_vehicles_by_family_dataframe,
    top_vehicles_by_pattern_dataframe,
    top_vehicles_global_dataframe,
    write_gold_csv_outputs,
    write_mvp_outputs,
    write_silver_parquet,
)
from tal_qual.smoke import SAMPLE_TEXT_PATH, load_sample_text

__all__ = [
    "BRONZE_OUTPUT_PATH",
    "ONE_SHARD_REFINED_TIER",
    "RAW_CORPUS_GLOB",
    "RAW_CORPUS_INPUT",
    "REFINED_CANDIDATES_NLP_OUTPUT_PATH",
    "SAMPLE_TEXT_PATH",
    "SAMPLE_DEBUG_TIER",
    "SILVER_OUTPUT_PATH",
    "build_nlp_parse_text",
    "connector_family_counts_dataframe",
    "extract_candidate_rows",
    "load_sample_text",
    "normalize_vehicle",
    "nlp_refinement_scope",
    "pattern_type_counts_dataframe",
    "prepare_bronze_dataframe",
    "prepare_refined_dataframe",
    "prepare_refined_dataframe_for_tier",
    "prepare_sample_debug_dataframe",
    "prepare_silver_dataframe",
    "refine_candidate_row",
    "refine_candidate_rows",
    "sample_examples_dataframe",
    "sample_debug_rows",
    "top_vehicles_by_family_dataframe",
    "top_vehicles_by_pattern_dataframe",
    "top_vehicles_global_dataframe",
    "write_bronze_parquet",
    "write_gold_csv_outputs",
    "write_mvp_outputs",
    "write_refined_parquet",
    "write_silver_parquet",
]
